encyclopedia/urls.py
# encyclopedia/urls.py

from django.urls import path
from . import views


app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("create/<str:page_title>", views.create, name="create"),
    path("edit/<str:page_title>", views.edit, name="edit"),
    path("404", views.page404, name="404"),
    path("search", views.search, name="search"),
    path("random", views.random_page, name="random"),
    path("<str:page_title>", views.wiki_page, name="wiki_page")    
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include("encyclopedia.urls"))
    path('wiki/', include("encyclopedia.urls"))
]

encyclopedia/controller.py
import re
from . import util
from . import markdown2


# ?????
def sub_title(title):
    title = re.sub('[^A-Za-z-1-9 -_]+', '', title)
    return title


# This method return the boolean
# as checks whether such a file already exists
def check_exists_pages(page_title):
    # page_title = sub_title(page_title)
    for i in range(len(util.list_entries())):
        le = util.list_entries()[i]        
        if le == page_title:
            return True
    return False


# This method return the value
# as checks whether such a file already exists
def matching(search_request):
    matching_title = [s for s in util.list_entries() if search_request in s]    
    return matching_title


def converted_entry_content(page_title):
    return markdown2.Markdown().convert(util.get_entry(page_title))


def content(page_title, entries, exist):
    context = {
        "page_title": page_title,
        "page_content": converted_entry_content(page_title),
        "exist": exist,
        "entries": entries
    }
    return context


def if_matching(search_request):
    a = False
    if any(search_request in s for s in util.list_entries()):
        a = True
    return a


def title_replacer(title):
    for i in ['~', '`', '\\', '|', '/','+','@','#','!','$','%','^', '*','(',')','{','}','[',']', '<', '>']:
        title = title.replace(i, '')
    return title

encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.template.defaultfilters import random
from . import util, controller, controller_search, controller_edit


# index page
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def wiki_page(request, page_title):
    # page_title = page_title.capitalize()
    if not controller.check_exists_pages(page_title):
        return HttpResponseRedirect(reverse("encyclopedia:404"))
    else:
        return render(request, "encyclopedia/page.html",
                      controller.content(
                          page_title,
                          util.list_entries(),
                          controller.check_exists_pages(page_title)))


def random_page(request):
    return render(request,
                  "encyclopedia/page.html",
                  controller.content(random(util.list_entries()),
                                     util.list_entries(), True))


# Register sensitive search
def search(request):
    return controller_search.searcher(request)


def create(request, page_title):
    page_title = " "
    action = False
    return controller_edit.editor(request, page_title, action)


def edit(request, page_title):
    action = True
    return controller_edit.editor(request, page_title, action)


def page404(request):
    return render(request, "encyclopedia/page404.html", {
        "entries": util.list_entries(),
        "count": len(util.list_entries())
    })

encyclopedia/templates/encyclopedia/Test.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="styles _m.css" rel="stylesheet">
        <link rel="shortcut icon" href="{% static 'encyclopedia/img/favicon.ico' %}" type="image/x-icon">
    </head>
    <body>
        <div class="bg">
        <div class="row">
            <div class="../../sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form method="GET" action="{% url 'encyclopedia:search' %}">
                    <input class="search" type="text" name="q" value="{{ request.GET.q }}" placeholder="Search Encyclopedia">
                    <button class="btn btn-success" type="submit">Search</button>
                </form>
                <div>
                    <a class="btn btn-info"  href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a class="btn btn-info" href="{% url 'encyclopedia:editor' %}">Create New Page</a>
                </div>
                <div>
                    <a class="btn btn-info" href="{% url 'encyclopedia:random' %}">Random Page</a>
                    
                </div>
                block nav
                
            </div>
            <div class="main col-lg-10 col-md-9">
                block body
              
            </div>
        </div>
</div>
    </body>
</html>

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia editor
{% endblock %}

{% block body %}
    <br>
    {% if action == True %}
        <h1>Page edit <b>{{ page_title }}</b></h1>
    {% elif action == False %}
        <h1>Create <b>New page</b></h1>
    {% endif %}

<div id="editor" class="editor col-md-12">
            {% include 'encyclopedia/messages.html' %}         
            {% if action == True %}
        <form action="{% url 'encyclopedia:edit' page_title %}" method="POST" class="form-horizontal form-bordered">            
            <input name="title_name"  type="text"  maxlength="200" required id="title_name" value="{{ page_title }}" hidden >
       
            {% elif action == False %}
        <form action="{% url 'encyclopedia:create' page_title %}" method="POST"  class="form-horizontal form-bordered">     
            <input name="title_name"  type="text"  maxlength="200" required id="title_name" value="" class="form-control">

            {% endif %}
            <br>
            <br>
            <textarea  name="content"  cols="40" rows="10" required="" id="content" spellcheck="false" class="form-control">{{ pure_content | safe }}</textarea>
            <br>
            <br>
            {% csrf_token %}
            <button class="btn btn-primary" type="submit", name="save">Save edition</button>
            <br>
        </form>
        <br>
        <a class="btn btn-primary"  href="{% url 'encyclopedia:index' %}">Cancel</a>
</div>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
   Wiki as Encyclopedia Home page
{% endblock %}

{% block body %}

<div class="col-md-12 center">
    <h2 class="mt-xlg mb-none"><strong>Wiki</strong> encyclopedia</h2>
    <p class="lead">welcome <span class="alternative-font font-size-xl">...all demos included!</span></p>
</div>

<div class="col-md-12">
<div class="heading heading-border heading-middle-border">
    <h2>All <strong>Pages</strong></h2>
</div>
</div>

    <h1></h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{{ entry }}">{{ entry }}</a> </li>
            {% empty %}
            <li>no pages</li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en" class="side-header">

<head>

    <!-- Basic -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>{% block title %}{% endblock %}</title>

    <meta name="keywords" content="" />
    <meta name="description" content="">
    <meta name="author" content="AlexSonar">

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'encyclopedia/img/favicon.ico' %}" type="image/x-icon">
    <link rel="apple-touch-icon" href="img/apple-touch-icon.png">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <!-- Web Fonts  -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CShadows+Into+Light"
        rel="stylesheet" type="text/css">

    <!-- Vendor CSS -->
    <link rel="stylesheet" href="{% static 'encyclopedia/vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'encyclopedia/vendor/font-awesome/css/font-awesome.min.css' %}">
    <!-- <link rel="stylesheet" href="vendor/animate/animate.min.css"> -->
    <link rel="stylesheet" href="{% static 'encyclopedia/vendor/simple-line-icons/css/simple-line-icons.min.css' %}">
    <!-- <link rel="stylesheet" href="vendor/magnific-popup/magnific-popup.min.css"> -->
    <link rel="stylesheet" href="{% static 'encyclopedia/vendor/theme/css/theme.css' %}">
    <link rel="stylesheet" href="{% static 'encyclopedia/vendor/theme/css/theme-elements.css' %}">


    <!-- Theme CSS -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->

    <link href="{% static 'encyclopedia/main.css' %}" rel="stylesheet">
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    <!-- <link href="{% static 'encyclopedia/vendor/theme/css/main.css' %}" rel="stylesheet"> -->

</head>

<body class="bg_grad">
    <div class="bg1 bg_grad">
        <div class="bg3"></div>
    </div>
    <div class="body">
        <header id="header"
            data-plugin-options="{'stickyEnabled': true, 'stickyEnableOnBoxed': false, 'stickyEnableOnMobile': true, 'stickyStartAt': 57, 'stickySetTop': '-57px', 'stickyChangeLogo': true}">
            <div class="header-body">
                <div class="header-container container">
                    <div class="header-row">
                        <div class="header-column">
                            <div class="header-logo">
                                <a href="{% url 'encyclopedia:index' %}">
                                    <img alt="wiki-encyclopedia-logo" width="111" height="54" data-sticky-width="82"
                                        data-sticky-height="40" data-sticky-top="33"
                                        src="{% static 'encyclopedia/img/wiki-logo.png' %}">
                                </a>
                            </div>
                        </div>
                        <div class="header-column">
                            <div class="header-row">
                                <div class="header-search hidden-xs">
                                    <form method="GET" id="searchForm" action="{% url 'encyclopedia:search' %}">
                                        <div class="input-group">
                                            <input class="form-control" type="text" id="q" name="q"
                                                value="{{ request.GET.q }}" maxlength="200" spellcheck="false"
                                                autocapitalize="off" role="combobox" placeholder="Search Encyclopedia">
                                            <span class="input-group-btn">
                                                <button class="btn btn-default" type="submit"><i
                                                        class="fa fa-search"></i></button>
                                            </span>
                                        </div>
                                    </form>
                                </div>
                                <br>
                            </div>
                            <div class="header-row">
                                <div class="header-nav">
                                    <button class="btn header-btn-collapse-nav" data-toggle="collapse"
                                        data-target=".header-nav-main">
                                        <i class="fa fa-bars"></i>
                                    </button>
                                    <div
                                        class="header-nav-main header-nav-main-effect-1 header-nav-main-sub-effect-1 collapse">
                                        <nav>
                                            <ul class="nav nav-pills" id="mainNav">
                                                <li class="dropdown active">
                                                    <a class="dropdown-toggle" href="{% url 'encyclopedia:index' %}">
                                                        Home
                                                    </a>
                                                </li>
                                                <li class="">
                                                    <a href="{% url 'encyclopedia:create' 'new' %}">
<!--                                                    <a href="{% url 'encyclopedia:edit' 'new' %}">-->
                                                        Create New Page
                                                    </a>
                                                </li>
                                                <li class="">
                                                    <a href="{% url 'encyclopedia:random' %}">
                                                        Random Page
                                                    </a>
                                                </li>
                                                <!-- <li class="dropdown">
                                                    <a class="dropdown-toggle" href="#">
                                                        Categories
                                                    </a>
                                                    <ul class="dropdown-menu">
                                                        <li class="dropdown-submenu">
                                                            <a href="#">Headers</a>
                                                            <ul class="dropdown-menu">
                                                                <li class="dropdown-submenu">
                                                                    <a href="#">Default</a>
                                                                    <ul class="dropdown-menu">
                                                                        <li><a href="#">Default</a></li>
                                                                        <li><a href="#">Default + Language Dropdown</a>
                                                                        </li>
                                                                        <li><a href="#">Default + Big Logo</a></li>
                                                                    </ul>
                                                                </li>
                                                            </ul>
                                                        </li>
                                                    </ul>
                                                </li> -->
                                            </ul>
                                        </nav>
                                    </div>
                                    <!-- <ul class="header-social-icons social-icons hidden-xs hidden-sm">
                                        <li class="social-icons-facebook"><a href="http://www.facebook.com/"
                                                target="_blank" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                                        <li class="social-icons-twitter"><a href="http://www.twitter.com/"
                                                target="_blank" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                                        <li class="social-icons-linkedin"><a href="http://www.linkedin.com/"
                                                target="_blank" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                                    </ul> -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        <div role="main" class="main">

            {% block nav %}
            {% endblock %}

            <div class="main col-lg-10 col-md-9 page_frame">
                
                {% block body %}
                {% endblock %}

            </div>
        </div>
    </div>

    <!-- Vendor -->
    <script src="{% static 'encyclopedia/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <script src="{% static 'encyclopedia/vendor/jquery/jquery.min.js' %}"></script>
    <!-- <script src="vendor/jquery.appear/jquery.appear.min.js"></script>
    <script src="vendor/jquery.easing/jquery.easing.min.js"></script>
    <script src="vendor/jquery-cookie/jquery-cookie.min.js"></script>

    <script src="vendor/common/common.min.js"></script>
    <script src="vendor/jquery.validation/jquery.validation.min.js"></script>
    <script src="vendor/jquery.easy-pie-chart/jquery.easy-pie-chart.min.js"></script>
    <script src="vendor/jquery.gmap/jquery.gmap.min.js"></script>
    <script src="vendor/jquery.lazyload/jquery.lazyload.min.js"></script>
    <script src="vendor/isotope/jquery.isotope.min.js"></script>
    <script src="vendor/owl.carousel/owl.carousel.min.js"></script>
    <script src="vendor/magnific-popup/jquery.magnific-popup.min.js"></script>
    <script src="vendor/vide/vide.min.js"></script> -->

    <!-- Theme Base, Components and Settings -->
    <!-- <script src="js/theme.js"></script> -->

    <!-- Current Page Vendor and Views -->
    <!-- <script src="vendor/rs-plugin/js/jquery.themepunch.tools.min.js"></script>
    <script src="vendor/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
    <script src="vendor/circle-flip-slideshow/js/jquery.flipshow.min.js"></script>
    <script src="js/views/view.home.js"></script> -->

    <!-- Theme Custom -->
    <!-- <script src="js/custom.js"></script> -->

    <!-- Theme Initialization Files -->
    <!-- <script src="js/theme.init.js"></script> -->


</body>

</html>

encyclopedia/templates/encyclopedia/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} ma" id="msg" role="alert">
            {{ message |safe  }}
            <br>
            <br>
            <div> 
                <a class="btn btn-primary" href="{% url 'encyclopedia:edit' page_title %}">Edit <b>{{ page_title }}</b> page</a> 
            </div>
        </div>
    {% endfor %}
{% endif %}    

encyclopedia/templates/encyclopedia/page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia {{ page_title  }}
{% endblock %}

{% block body %}
    {% if exist %}
<!--edit/{{ page_title }}&action=edit-->
    <div> 
        <a class="btn btn-primary" href="{% url 'encyclopedia:edit' page_title %}">Edit <b>{{ page_title }}</b> page</a> 
    </div>
    
        {{ page_content |safe }}      
        <form action="q">

        </form>
        
    {% else %}
        <H1> No </H1>
        <h1>All Pages</h1>
        <ul>
            {% for entry in entries %}
            <li><a href="{{entry}}">{{ entry }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

encyclopedia/templates/encyclopedia/page404.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h2>404 Page </h2>
    <h1>Oops!</h1>
    <h3>The page you requested was not found!</h3>
    <br>
    <br>
    <h4>You might be interested in {{ count }} pages, further below:</h4>    
    <br>
    <ul>
        {% for entry in entries %}
        <li><a href="{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}